import type { Metadata } from "next";
import Nav from "@/components/nav";
import SiteFooter from "@/components/site-footer";

export const metadata: Metadata = {
  title: "SiteFlow Subprocessors",
  description:
    "The third-party service providers SiteFlow uses to host, operate, and deliver the platform, and what data they may process.",
  alternates: { canonical: "/subprocessors" },
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "August 22, 2026";

const SUBPROCESSORS = [
  {
    name: "Vercel",
    purpose: "Application hosting and delivery",
    data: "All web and API traffic to SiteFlow",
    link: "https://vercel.com/legal/privacy-policy",
  },
  {
    name: "Supabase",
    purpose: "Database, authentication, and backend storage",
    data: "Account data and the data generated by whichever SiteFlow tools you use",
    link: "https://supabase.com/privacy",
  },
  {
    name: "Groq",
    purpose: "AI inference for the chatbot tool",
    data: "Chatbot persona, trained website content, and visitor chat messages",
    link: "https://groq.com/privacy-policy/",
  },
  {
    name: "Patreon",
    purpose: "Subscription billing and payment processing",
    data: "Email address and plan/tier status — SiteFlow does not handle card details directly",
    link: "https://www.patreon.com/policy/privacy",
  },
  {
    name: "Clickadilla",
    purpose: "Ad network shown on free tool pages only (not paid tools, dashboard, or embeds)",
    data: "Visitor IP address, browser/device info; may set cookies to serve and measure ads",
    link: "https://publishers.clickadilla.com/privacy-policy",
  },
  {
    name: "Monetag",
    purpose: "Ad network shown on free tool pages only (not paid tools, dashboard, or embeds)",
    data: "Visitor IP address, browser/device info; may set cookies to serve and measure ads",
    link: "https://monetag.com/privacy/",
  },
];

export default function SubprocessorsPage() {
  return (
    <div className="min-h-screen">
      <Nav />
      <main className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="text-3xl font-bold tracking-tight">Subprocessors</h1>
        <p className="mt-2 text-sm text-slate">Last updated: {LAST_UPDATED}</p>

        <p className="mt-8 text-sm leading-relaxed text-ink">
          SiteFlow uses a small number of third-party service providers to host, operate,
          secure, and bill for parts of the platform. These providers may process customer or
          personal data as necessary to provide their service to us. This list reflects the
          providers we actually use in production — not every service we've ever tried.
        </p>

        <div className="mt-8 overflow-x-auto">
          <table className="w-full min-w-[560px] border-collapse text-sm">
            <thead>
              <tr className="border-b border-line text-left text-xs uppercase tracking-wide text-slate">
                <th className="py-2 pr-4">Provider</th>
                <th className="py-2 pr-4">Purpose</th>
                <th className="py-2 pr-4">Data potentially processed</th>
                <th className="py-2">Privacy page</th>
              </tr>
            </thead>
            <tbody className="text-ink">
              {SUBPROCESSORS.map((sp) => (
                <tr key={sp.name} className="border-b border-line align-top">
                  <td className="py-3 pr-4 font-medium">{sp.name}</td>
                  <td className="py-3 pr-4 text-slate">{sp.purpose}</td>
                  <td className="py-3 pr-4 text-slate">{sp.data}</td>
                  <td className="py-3">
                    <a
                      href={sp.link}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-brand underline"
                    >
                      View
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <p className="mt-8 text-sm leading-relaxed text-ink">
          GitHub is used to store SiteFlow&apos;s source code during development. It doesn&apos;t
          process customer data and isn&apos;t part of the production data path, so it isn&apos;t
          listed as a subprocessor above.
        </p>

        <p className="mt-8 text-sm text-slate">
          Changes to this list will be reflected on this page as SiteFlow&apos;s infrastructure
          changes.
        </p>
        <p className="mt-2 text-xs text-slate">Last updated: {LAST_UPDATED}</p>
      </main>
      <SiteFooter />
    </div>
  );
}
